api_platform:
    title: 'Symfony REST API'
    description: 'NINEA-CUCI app with Symfony API REST .'
    version: '1.0.0'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
      