# app/config/config.yml (or config/packages/knp_snappy.yaml if using Symfony4 and the Flex recipe)
knp_snappy:
    # temporary_folder: "%kernel.cache_dir%/snappy" uncomment on ubuntu
    process_timeout: 20 # In seconds

    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%' # /usr/local/bin/wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
        # binary:     '%kernel.project_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
        options:       
            - { name: 'viewport-size', value: '1024x768'}
            - { name: 'page-size', value: 'A4'}
            - { name: 'encoding', value: 'UTF-8'}
            - { name: 'images', value: true}
            - { name: 'default-header', value: null}
            - { name: 'background', value: true}
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%' # /usr/local/bin/wkhtmltoimage #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
        options:    []
